### PR TITLE
feat(readme): Updating features implemented.

### PR DESCRIPTION
**Pull request by deonna**

### CODE REVIEW

**Comment by codepathreview** [comment]
Hello Deonna, 
Great to see you were able to augment your app with many extensions now. As mentioned earlier, the extension tasks available on each project are often the most valuable learning since they dive deeper into common real-world Android use cases.

We'll be in touch with you again soon via email. Let us know if you have any questions about the project or anything in the meantime, you can always reach us at <admissions@codepath.com>.

**Comment by deonna** [comment]
@codepathreview Updated my submission with the gif located [here](http://i.imgur.com/nEQFiOn.gif).

Thanks! 🎉

**Comment by nesquena** [comment]
Good chatting with you yesterday. Your pre-work is awesome too, really nice job pushing into all the optionals and going deeper with your own tasks. Hope you enjoyed the pre-work and we'll be in touch again soon!

**Comment by deonna** [comment]
@nesquena - I just got the news. Thank you so much for the opportunity! 😄  🎉

**Comment by nesquena** [comment]
👍 Sure, looking forward to getting started soon with the new cohort!

**Pull request merged**
